name: DEV

on:
  pull_request:
    branches: [ development ]

env:
  APP_PATH: androidApp
  SECRET_PATH: secret
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradle executable
        run: chmod +x ./gradlew

#      - name: Install bundle
#        run: |
#          bundle config path vendor/bundle
#          bundle install --jobs 4 --retry 3
      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > uwang-keystore.b64
          base64 -d -i uwang-keystore.b64 > "$SECRET_PATH"/uwang-keystore
          echo "$GRADLE_PROPERTIES" >> gradle.properties
          echo "$GOOGLE_SERVICES" >> "$APP_PATH"/google-services.json

#          echo "storeFile=../secret/uwang-keystore" >> gradle.properties
#          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> gradle.properties
#          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> gradle.properties
#          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> gradle.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
#          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
#          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
#          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
      - name: Detekt
        run: ./gradlew detekt

      - name: Build with Gradle
        run: ./gradlew assembleRelease lintDebug --stacktrace

      - name: Upload build output(APKs)
        uses: actions/upload-artifact@v3
        with:
          name: build-outputs
          path: ${{env.APP_PATH}}/build/outputs