name: STAGING

on:
  push:
    branches: [ staging ]

env:
  APP_PATH: androidApp
  SECRET_PATH: secret
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle

      - name: Cache Gradle and wrapper
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Configure Keystore
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > uwang-keystore.b64
          base64 -d -i uwang-keystore.b64 > "$SECRET_PATH"/uwang-keystore
          echo "$GRADLE_PROPERTIES" >> gradle.properties
          echo "$GOOGLE_SERVICES" >> "$APP_PATH"/google-services.json
          echo "$GOOGLE_CREDENTIAL" >> "$SECRET_PATH"/uwang-app-distribution.json

        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
          GOOGLE_CREDENTIAL: ${{ secrets.GOOGLE_CREDENTIAL }}
          GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      - name: Detekt
        run: ./gradlew detekt

      - name: Build with Gradle
        run: ./gradlew  assembleDebug appDistributionUploadStagingDebug --stacktrace